ALTER TABLE "content"."instrument" ADD COLUMN "order" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (sequence name "content"."instrument_order_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "content"."instrument" ADD CONSTRAINT "instrument_order_unique" UNIQUE("order") DEFERRABLE INITIALLY DEFERRED;
