import type * as React from 'react';

import { Outfit } from 'next/font/google';

import './global.css';

// https://nextjs.org/docs/app/building-your-application/optimizing/fonts
const font = Outfit({
  display: 'swap',
  variable: '--font-outfit',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Custom head elements */}
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={`bg-base text-foreground ${font.variable} font-sans`}>
        {children}
      </body>
    </html>
  );
}
